const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY='controlClasesSimple_v2';
const fresh=()=>({settings:{owner:'Matías Montoya',initial:0,initialDate:''},students:[],classes:[],payments:[]});
let data=load(), route='home';
function load(){try{return {...fresh(),...JSON.parse(localStorage.getItem(KEY)||'null')}}catch(e){return fresh()}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function id(p){return p+'_'+Date.now()+'_'+Math.random().toString(36).slice(2,6)}
function today(){let d=new Date();return d.toISOString().slice(0,10)}
function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(+n||0)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function date(s){let d=new Date(s+'T12:00:00');return isNaN(d)?'—':d.toLocaleDateString('es-EC',{day:'2-digit',month:'short',year:'numeric'})}
function cap(s=''){return s? s[0].toUpperCase()+s.slice(1):''}
function mins(a,b){if(!a||!b)return 0;let [h1,m1]=a.split(':').map(Number),[h2,m2]=b.split(':').map(Number),x=h2*60+m2-h1*60-m1;return x<0?x+1440:x}
function dur(n){let h=Math.floor(n/60),m=n%60;return h?(m?`${h} h ${m} min`:`${h} h`):`${m} min`}
function monday(s=today()){let d=new Date(s+'T12:00:00'),x=(d.getDay()+6)%7;d.setDate(d.getDate()-x);return d.toISOString().slice(0,10)}
function sunday(s){let d=new Date(monday(s)+'T12:00:00');d.setDate(d.getDate()+6);return d.toISOString().slice(0,10)}
function monthBounds(m=today().slice(0,7)){let a=m+'-01',d=new Date(a+'T12:00:00');d.setMonth(d.getMonth()+1);d.setDate(0);return[a,d.toISOString().slice(0,10)]}
function total(end='9999-12-31'){return (+data.settings.initial||0)+data.classes.filter(x=>x.date<=end).reduce((s,x)=>s+(+x.value||0),0)-data.payments.filter(x=>x.date<=end).reduce((s,x)=>s+(+x.amount||0),0)}
function stats(a,b){let c=data.classes.filter(x=>x.date>=a&&x.date<=b),p=data.payments.filter(x=>x.date>=a&&x.date<=b);return{c,p,h:c.filter(x=>x.status==='impartida').reduce((s,x)=>s+mins(x.start,x.end),0),g:c.reduce((s,x)=>s+(+x.value||0),0),r:p.reduce((s,x)=>s+(+x.amount||0),0),bal:total(b)}}
function nav(r){route=r;$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===r));render()}
$$('.nav-item').forEach(b=>b.onclick=()=>nav(b.dataset.route)); $('#settingsBtn').onclick=settings;
function render(){let t={home:'Inicio',classes:'Clases',payments:'Pagos',reports:'Reportes'};$('#pageTitle').textContent=t[route];({home,classes,payments,reports}[route])()}
function home(){let a=monday(),b=sunday(a),s=stats(a,b),mov=[...data.classes.map(x=>({date:x.date,time:x.start,label:'Clase · '+(x.students.join(', ')||'Sin alumno'),amt:+x.value||0})),...data.payments.map(x=>({date:x.date,time:'23:59',label:'Pago · '+cap(x.method),amt:-(+x.amount||0)}))];if(+data.settings.initial)mov.push({date:data.settings.initialDate||today(),time:'00:00',label:'Saldo inicial',amt:+data.settings.initial});mov.sort((x,y)=>(x.date+x.time).localeCompare(y.date+y.time));mov=mov.slice(-5).reverse();$('#view').innerHTML=`<section class="hero"><div class="hero-label">Saldo pendiente</div><div class="balance">${money(total())}</div><div class="hero-help">Lo que el club debe actualmente.</div></section><section class="metrics"><div class="metric"><small>Horas esta semana</small><strong>${dur(s.h)}</strong></div><div class="metric"><small>Generado</small><strong>${money(s.g)}</strong></div><div class="metric"><small>Recibido</small><strong>${money(s.r)}</strong></div></section><section class="quick-actions"><button class="primary" id="qClass">+ Registrar clase</button><button class="secondary" id="qPay">Registrar pago</button></section><div class="section-head"><h2>Últimos movimientos</h2></div>${mov.length?mov.map(x=>`<div class="card"><div class="row"><div><strong>${esc(x.label)}</strong><div class="muted">${date(x.date)}${x.time!=='23:59'&&x.time!=='00:00'?' · '+x.time:''}</div></div><div class="${x.amt<0?'amount-minus':'amount-plus'}">${x.amt<0?'−':'+'}${money(Math.abs(x.amt))}</div></div></div>`).join(''):'<div class="empty">Todavía no hay movimientos.</div>'}`;$('#qClass').onclick=()=>classForm();$('#qPay').onclick=()=>payForm()}
function classes(){let list=[...data.classes].sort((a,b)=>(b.date+b.start).localeCompare(a.date+a.start));$('#view').innerHTML=`<div class="quick-actions"><button class="primary" id="addClass">+ Registrar clase</button><button class="secondary" id="students">Alumnos</button></div><div class="section-head"><h2>Historial</h2><span class="muted">${list.length}</span></div>${list.length?list.map(x=>`<div class="card"><div class="row"><div><strong>${esc(x.students.join(', '))}</strong><div class="muted">${date(x.date)} · ${x.start}–${x.end} · ${dur(mins(x.start,x.end))}</div></div><strong>${money(x.value)}</strong></div><div class="row"><span class="pill">${cap(x.status)}</span><div class="list-actions"><button class="mini" data-e="${x.id}">Editar</button><button class="mini" data-d="${x.id}">Eliminar</button></div></div></div>`).join(''):'<div class="empty">No hay clases todavía.</div>'}`;$('#addClass').onclick=()=>classForm();$('#students').onclick=students;$$('[data-e]').forEach(b=>b.onclick=()=>classForm(b.dataset.e));$$('[data-d]').forEach(b=>b.onclick=()=>{if(confirm('¿Eliminar esta clase?')){data.classes=data.classes.filter(x=>x.id!==b.dataset.d);save()}})}
function classForm(i){let x=i?data.classes.find(v=>v.id===i):null,selected=[...(x?.students||[])],status=x?.status||'impartida';modal(`<div class="modal-head"><h2>${x?'Editar':'Nueva'} clase</h2><button class="close-btn" id="x">×</button></div><div class="form"><label>Fecha<input id="d" type="date" value="${x?.date||today()}"></label><div class="inline"><label>Desde<input id="a" type="time" value="${x?.start||''}"></label><label>Hasta<input id="b" type="time" value="${x?.end||''}"></label></div><div class="student-picker"><label>Alumno(s)</label><div class="student-add"><input id="student" placeholder="Escribe un nombre"><button id="plus" type="button">+</button></div><div id="picked" class="chips"></div><div id="quick" class="quick-students"></div></div><label>Estado</label><div class="segmented">${['impartida','cancelada','ausencia'].map(v=>`<button type="button" data-s="${v}" class="${status===v?'active':''}">${cap(v)}</button>`).join('')}</div><label>Valor generado (USD)<input id="val" type="number" min="0" step="0.01" inputmode="decimal" placeholder="Ej. 20.00" value="${x?.value??''}"></label><div id="hint" class="banner"></div><button class="primary" id="saveClass" type="button">Guardar clase</button></div>`);$('#x').onclick=close;function draw(){ $('#picked').innerHTML=selected.map((n,j)=>`<span class="chip">${esc(n)} <button data-r="${j}">×</button></span>`).join('');$$('[data-r]').forEach(b=>b.onclick=()=>{selected.splice(+b.dataset.r,1);draw()});$('#quick').innerHTML=data.students.filter(n=>!selected.includes(n)).slice(0,8).map(n=>`<button data-q="${esc(n)}">${esc(n)}</button>`).join('');$$('[data-q]').forEach(b=>b.onclick=()=>{selected.push(b.dataset.q);draw()});hint()}function add(){let n=$('#student').value.trim();if(!n)return;if(!selected.includes(n))selected.push(n);if(!data.students.includes(n))data.students.push(n);$('#student').value='';draw()}$('#plus').onclick=add;$('#student').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();add()}};$$('[data-s]').forEach(b=>b.onclick=()=>{status=b.dataset.s;$$('[data-s]').forEach(z=>z.classList.toggle('active',z===b))});function hint(){let m=mins($('#a').value,$('#b').value);$('#hint').textContent=m?`${dur(m)}${selected.length?' · '+selected.length+' alumno(s)':''}`:'Ingresa hora de inicio y fin.'}$('#a').oninput=hint;$('#b').oninput=hint;$('#saveClass').onclick=()=>{let d=$('#d').value,a=$('#a').value,b=$('#b').value,v=+$('#val').value||0;if(!d||!a||!b)return alert('Completa fecha y horario.');if(!mins(a,b))return alert('La duración debe ser mayor a cero.');if(!selected.length)return alert('Agrega al menos un alumno.');if(status==='impartida'&&v<=0)return alert('Ingresa el valor generado.');let obj={id:i||id('c'),date:d,start:a,end:b,students:selected,status,value:v};if(i)data.classes[data.classes.findIndex(z=>z.id===i)]=obj;else data.classes.push(obj);close();save()};draw()}
function students(){modal(`<div class="modal-head"><h2>Alumnos</h2><button class="close-btn" id="x">×</button></div><div class="form"><div class="student-add"><input id="new" placeholder="Nombre del alumno"><button id="plus">+</button></div><div id="list"></div></div>`);$('#x').onclick=close;function draw(){let l=[...data.students].sort();$('#list').innerHTML=l.length?l.map(n=>`<div class="card"><div class="row"><strong>${esc(n)}</strong><button class="mini" data-rm="${esc(n)}">Quitar</button></div></div>`).join(''):'<div class="empty">No hay alumnos guardados.</div>';$$('[data-rm]').forEach(b=>b.onclick=()=>{data.students=data.students.filter(n=>n!==b.dataset.rm);localStorage.setItem(KEY,JSON.stringify(data));draw()})}$('#plus').onclick=()=>{let n=$('#new').value.trim();if(n&&!data.students.includes(n)){data.students.push(n);$('#new').value='';localStorage.setItem(KEY,JSON.stringify(data));draw()}};draw()}
function payments(){let l=[...data.payments].sort((a,b)=>b.date.localeCompare(a.date));$('#view').innerHTML=`<div class="quick-actions"><button class="primary" id="add">+ Registrar pago</button><button class="secondary" id="saldo">Ver saldo</button></div><div class="section-head"><h2>Pagos recibidos</h2></div>${l.length?l.map(p=>`<div class="card"><div class="row"><div><strong>${money(p.amount)}</strong><div class="muted">${date(p.date)} · ${cap(p.method)}</div></div><div class="list-actions"><button class="mini" data-e="${p.id}">Editar</button><button class="mini" data-d="${p.id}">Eliminar</button></div></div></div>`).join(''):'<div class="empty">Todavía no hay pagos.</div>'}`;$('#add').onclick=()=>payForm();$('#saldo').onclick=()=>nav('home');$$('[data-e]').forEach(b=>b.onclick=()=>payForm(b.dataset.e));$$('[data-d]').forEach(b=>b.onclick=()=>{if(confirm('¿Eliminar este pago?')){data.payments=data.payments.filter(x=>x.id!==b.dataset.d);save()}})}
function payForm(i){let p=i?data.payments.find(x=>x.id===i):null;modal(`<div class="modal-head"><h2>${p?'Editar':'Registrar'} pago</h2><button class="close-btn" id="x">×</button></div><div class="form"><label>Fecha<input id="d" type="date" value="${p?.date||today()}"></label><label>Monto recibido (USD)<input id="amt" type="number" min="0.01" step="0.01" inputmode="decimal" value="${p?.amount||''}"></label><label>Medio<select id="m"><option value="transferencia">Transferencia</option><option value="efectivo">Efectivo</option><option value="otro">Otro</option></select></label><button class="primary" id="savePay" type="button">Guardar pago</button></div>`);$('#x').onclick=close;if(p)$('#m').value=p.method;$('#savePay').onclick=()=>{let a=+$('#amt').value||0;if(!$('#d').value||a<=0)return alert('Completa fecha y monto.');let o={id:i||id('p'),date:$('#d').value,amount:a,method:$('#m').value};if(i)data.payments[data.payments.findIndex(x=>x.id===i)]=o;else data.payments.push(o);close();save()}}
function reports(){let w=monday(),m=today().slice(0,7);$('#view').innerHTML=`<div class="card"><div class="section-head" style="margin-top:0"><h2>Semana</h2></div><label>Semana que comienza<input id="week" type="date" value="${w}"></label><div id="wb"></div></div><div class="card"><div class="section-head" style="margin-top:0"><h2>Mes</h2></div><label>Mes<input id="month" type="month" value="${m}"></label><div id="mb"></div></div>`;function block(a,b){let s=stats(a,b);return `<div class="muted" style="margin:8px 0 12px">${date(a)} – ${date(b)}</div><div class="report-grid"><div class="metric"><small>Horas</small><strong>${dur(s.h)}</strong></div><div class="metric"><small>Generado</small><strong>${money(s.g)}</strong></div><div class="metric"><small>Recibido</small><strong>${money(s.r)}</strong></div><div class="metric"><small>Saldo al cierre</small><strong>${money(s.bal)}</strong></div></div>`}function rw(){let a=monday($('#week').value),b=sunday(a);$('#wb').innerHTML=block(a,b)}function rm(){let [a,b]=monthBounds($('#month').value);$('#mb').innerHTML=block(a,b)}$('#week').onchange=rw;$('#month').onchange=rm;rw();rm()}
function settings(){modal(`<div class="modal-head"><h2>Configuración</h2><button class="close-btn" id="x">×</button></div><div class="form"><section class="settings-section"><h3>Saldo inicial</h3><p>Lo que el club ya debía antes de empezar a usar la app. Puedes corregirlo cuando quieras.</p><div class="inline"><label>Monto pendiente<input id="bal" type="number" step="0.01" inputmode="decimal" value="${+data.settings.initial||''}"></label><label>Fecha<input id="bd" type="date" value="${data.settings.initialDate||today()}"></label></div><button class="primary" id="saveBal" style="width:100%;margin-top:10px">Guardar saldo inicial</button></section><details><summary>Datos y respaldo</summary><div class="form" style="margin-top:12px"><label>Nombre para reportes<input id="owner" value="${esc(data.settings.owner)}"></label><button class="secondary" id="saveOwner">Guardar nombre</button><button class="secondary" id="backup">Exportar respaldo</button></div></details></div>`);$('#x').onclick=close;$('#saveBal').onclick=()=>{data.settings.initial=+$('#bal').value||0;data.settings.initialDate=$('#bd').value||today();close();save()};$('#saveOwner').onclick=()=>{data.settings.owner=$('#owner').value.trim()||'Matías Montoya';close();save()};$('#backup').onclick=()=>{let a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=u;a.download='control-clases-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}}
function modal(h){$('#modalCard').innerHTML=h;$('#modal').showModal()} function close(){if($('#modal').open)$('#modal').close()}
render();
